### ISSUE TITLE
Widevine CDM installation failed

### ISSUE THREAD

**Issue by gfelixwolf** [phate89/Mediaset-Play-plugin.video.videomediaset#23]
Great job, many thanks.
As by subject: Widevine installation proceeds up to the end of the download of the huge chromeos image, then exit.

Best

```
2020-05-11 23:30:12.998 T:4089700368  NOTICE: Starting Kodi (18.6 Git:6763f2b528974c6ab3a5fcc8b75f683db13c6bda). Platform: Linux ARM 32-bit
2020-05-11 23:30:12.998 T:4089700368  NOTICE: Using Release Kodi x32 build
2020-05-11 23:30:12.998 T:4089700368  NOTICE: Kodi compiled 2020-05-09 by GCC 8.3.0 for Linux ARM 32-bit version 3.14.29 (200221)
2020-05-11 23:30:12.998 T:4089700368  NOTICE: Running on CoreELEC (official): nightly_20200509 (9.2), kernel: Linux ARM 64-bit version 3.14.29 aarch64
2020-05-11 23:30:12.999 T:4089700368  NOTICE: FFmpeg version/source: 4.0.4-Kodi
2020-05-11 23:30:12.999 T:4089700368  NOTICE: Host CPU: Amlogic S912 rev a, 8 cores available
2020-05-11 23:30:12.999 T:4089700368  NOTICE: ARM Features: Neon enabled
...
2020-05-11 23:30:13.561 T:4089700368  NOTICE: ADDON: plugin.video.videomediaset v2.0.1~beta2 installed
...
2020-05-11 23:30:13.562 T:4089700368  NOTICE: ADDON: script.module.inputstreamhelper v0.4.7 installed
...
2020-05-11 23:30:13.562 T:4089700368  NOTICE: ADDON: script.module.phate89 v1.2.1~beta2 installed
...
2020-05-11 23:30:30.806 T:3286278976  NOTICE: plugin.video.videomediaset: Starting module 'Mediaset Play' version '2.0.1~beta2' with command '?pid=j4pB8G_XyyNv&mode=video'
2020-05-11 23:30:31.218 T:3286278976   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2020-05-11 23:30:31.926 T:3286278976  NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/cdm'.
2020-05-11 23:30:31.931 T:3286278976  NOTICE: Previous line repeats 1 times.
2020-05-11 23:30:31.931 T:3286278976 WARNING: [script.module.inputstreamhelper] Widevine CDM is not installed.
2020-05-11 23:30:32.364 T:3717153600   ERROR: Window Translator: Can't find window videossettings
2020-05-11 23:30:32.364 T:3717153600   ERROR: Window Translator: Can't find window musicsettings
2020-05-11 23:30:32.396 T:3717153600   ERROR: Window Translator: Can't find window picturessettings
2020-05-11 23:30:32.429 T:3717153600   ERROR: Window Translator: Can't find window weathersettings
2020-05-11 23:30:36.547 T:3286278976  NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp'.
2020-05-11 23:30:36.549 T:3286278976  NOTICE: [script.module.inputstreamhelper] Create directory '/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/mnt'.
2020-05-11 23:30:36.554 T:3286278976  NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/cdm'.
2020-05-11 23:30:36.559 T:3286278976  NOTICE: Previous line repeats 1 times.
2020-05-11 23:30:36.559 T:3286278976 WARNING: [script.module.inputstreamhelper] Widevine CDM is not installed.
2020-05-11 23:30:36.563 T:3286278976  NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/cdm'.
2020-05-11 23:30:36.565 T:3286278976  NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp'.
2020-05-11 23:30:37.799 T:3717153600  NOTICE: Previous line repeats 1 times.
2020-05-11 23:30:37.799 T:3717153600   ERROR: Window Translator: Can't find window videossettings
2020-05-11 23:30:37.799 T:3717153600   ERROR: Window Translator: Can't find window musicsettings
2020-05-11 23:30:37.863 T:3717153600   ERROR: Window Translator: Can't find window picturessettings
2020-05-11 23:30:37.864 T:3717153600   ERROR: Window Translator: Can't find window weathersettings
2020-05-11 23:30:53.580 T:3286278976  NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/backup'.
2020-05-11 23:30:57.413 T:3286278976  NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp'.
2020-05-11 23:32:05.630 T:4089700368  NOTICE: Previous line repeats 1 times.
2020-05-11 23:32:05.631 T:4089700368  NOTICE: Samba is idle. Closing the remaining connections
2020-05-12 00:26:40.176 T:3286278976   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'ssl.SSLError'>
                                            Error Contents: ('The read operation timed out',)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.videomediaset/default.py", line 5, in <module>
                                                km.main()
                                              File "/storage/.kodi/addons/plugin.video.videomediaset/resources/main.py", line 540, in main
                                                self.riproduci_video(params['pid'])
                                              File "/storage/.kodi/addons/plugin.video.videomediaset/resources/main.py", line 445, in riproduci_video
                                                if not is_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 407, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 362, in _check_drm
                                                return self.install_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 34, in clean_before_after
                                                result = func(self, *args, **kwargs)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 224, in install_widevine
                                                result = install_widevine_arm(backup_path())
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 202, in install_widevine_arm
                                                downloaded = http_download(url, message=localize(30022), checksum=arm_device['sha1'], hash_alg='sha1', dl_size=int(arm_device['zipfilesize']))  # Downloading the recovery image
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 103, in http_download
                                                chunk = req.read(chunk_size)
                                              File "/usr/lib/python2.7/socket.py", line 384, in read
                                              File "/usr/lib/python2.7/httplib.py", line 597, in read
                                              File "/usr/lib/python2.7/socket.py", line 384, in read
                                              File "/usr/lib/python2.7/ssl.py", line 754, in recv
                                              File "/usr/lib/python2.7/ssl.py", line 641, in read
                                            SSLError: ('The read operation timed out',)
                                            -->End of Python script error report<--
```

**Comment by phate89** [comment]
The widevine addon isnot developed by me. You can try in kodi forums to get help
