### ISSUE TITLE
Uomini & donne not working, playback error 

### ISSUE THREAD

**Issue by manuelwizard** [phate89/Mediaset-Play-plugin.video.videomediaset#57]
When i try to play Uomini&donne videos i get this error:

2021-06-12 13:14:42.604 T:1482322688   ERROR: Previous line repeats 3 times.
2021-06-12 13:14:42.604 T:1482322688   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xec' in position 95: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.videomediaset/default.py", line 5, in <module>
                                                km.main()
                                              File "/storage/.kodi/addons/plugin.video.videomediaset/resources/main.py", line 537, in main
                                                self.riproduci_video(params['pid'])
                                              File "/storage/.kodi/addons/plugin.video.videomediaset/resources/main.py", line 434, in riproduci_video
                                                data = self.med.OttieniDatiVideo(pid, live)
                                              File "/storage/.kodi/addons/plugin.video.videomediaset/resources/lib/mediaset.py", line 433, in OttieniDatiVideo
                                                root = ET.fromstring(text)
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1657, in feed
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xec' in position 95: ordinal not in range(128)
                                            -->End of Python script error report<--
2021-06-12 13:14:42.815 T:1937149376   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.videomediaset/?pid=BfM_Sj2hAh4o&mode=video]

Kodi 18 on librelec 9.2.7
Can you fix it? Thanks a lot!

**Comment by phate89** [comment]
fixed by https://github.com/phate89/Mediaset-Play-plugin.video.videomediaset/pull/55
