### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by MarcoViti** [phate89/Mediaset-Play-plugin.video.videomediaset#58]
Hi, i have problem with this add-on, i have try  2.0.7. and 2.0.8.beta... on Matrix, below I publish the log lines relating to the problem.

Error Type: <class 'AttributeError'>
Error Contents: module 'xbmc' has no attribute 'translatePath'
Traceback (most recent call last):
  File "C:\Users\ocifa\AppData\Roaming\Kodi\addons\plugin.video.videomediaset\default.py", line 2, in <module>
    from resources.main import KodiMediaset
  File "C:\Users\ocifa\AppData\Roaming\Kodi\addons\plugin.video.videomediaset\resources\main.py", line 5, in <module>
    from phate89lib import kodiutils, staticutils  # pylint: disable=import-error
  File "C:\Users\ocifa\AppData\Roaming\Kodi\addons\script.module.phate89\lib\phate89lib\kodiutils.py", line 19, in <module>
    PATH_T = xbmc.translatePath(PATH)
AttributeError: module 'xbmc' has no attribute 'translatePath'
-->End of Python script error report<--

**Comment by mirh** [comment]
Fixed by https://github.com/phate89/script.module.phate89/pull/3.

**Comment by phate89** [comment]
merged the pr. IT will be in the official repo soon
