### ISSUE TITLE
Exception ignored

### ISSUE THREAD

**Issue by strk** [phate89/Mediaset-Play-plugin.video.videomediaset#61]
Excerpt from the log:
```
2021-12-05 23:37:11.265 T:5213     INFO <general>: plugin.video.videomediaset: Starting module 'Mediaset Play Infinity' version '2.0.7+matrix.1' with command ''
2021-12-05 23:37:11.446 T:5213     INFO <general>: CPythonInvoker(17, /home/strk/.kodi/addons/plugin.video.videomediaset/default.py): script aborted
2021-12-05 23:37:11.446 T:5213    ERROR <general>: Exception ignored in: 
2021-12-05 23:37:11.446 T:5213    ERROR <general>: <module 'threading' from '/usr/lib/python3.6/threading.py'>
2021-12-05 23:37:11.446 T:5213    ERROR <general>: 
                                                   
2021-12-05 23:37:11.446 T:5213    ERROR <general>: Traceback (most recent call last):
                                                   
2021-12-05 23:37:11.446 T:5213    ERROR <general>:   File "/usr/lib/python3.6/threading.py", line 1290, in _shutdown
                                                   
2021-12-05 23:37:11.447 T:5213    ERROR <general>:     
2021-12-05 23:37:11.447 T:5213    ERROR <general>: tlock.release()
2021-12-05 23:37:11.447 T:5213    ERROR <general>: 
                                                   
2021-12-05 23:37:11.447 T:5213    ERROR <general>: SystemError
2021-12-05 23:37:11.447 T:5213    ERROR <general>: : 
2021-12-05 23:37:11.447 T:5213    ERROR <general>: <built-in method release of _thread.lock object at 0x7f99b3dbc120> returned a result with an error set
2021-12-05 23:37:11.447 T:5213    ERROR <general>: 
                                                   
2021-12-05 23:37:11.526 T:5213     INFO <general>: Python interpreter stopped
2021-12-05 23:37:15.909 T:5216     INFO <general>: initializing python engine.
2021-12-05 23:37:16.369 T:5216    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SystemError'>
                                                   Error Contents: initialization of etree did not return an extension module
                                                   Traceback (most recent call last):
                                                     File "/home/strk/.kodi/addons/plugin.video.videomediaset/default.py", line 2, in <module>
                                                       from resources.main import KodiMediaset
                                                     File "/home/strk/.kodi/addons/plugin.video.videomediaset/resources/main.py", line 3, in <module>
                                                       from resources.lib.mediaset import Mediaset
                                                     File "/home/strk/.kodi/addons/plugin.video.videomediaset/resources/lib/mediaset.py", line 3, in <module>
                                                       from phate89lib import rutils, staticutils  # pylint: disable=import-error
                                                     File "/home/strk/.kodi/addons/script.module.phate89/lib/phate89lib/rutils.py", line 8, in <module>
                                                       from bs4 import BeautifulSoup
                                                     File "/home/strk/.kodi/addons/script.module.beautifulsoup4/lib/bs4/__init__.py", line 30, in <module>
                                                       from .builder import builder_registry, ParserRejectedMarkup
                                                     File "/home/strk/.kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/__init__.py", line 519, in <module>
                                                       from . import _lxml
                                                     File "/home/strk/.kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/_lxml.py", line 16, in <module>
                                                       from lxml import etree
                                                   SystemError: initialization of etree did not return an extension module
                                                   -->End of Python script error report<--
                                                   
2021-12-05 23:37:16.424 T:5216     INFO <general>: Python interpreter stopped
2021-12-05 23:37:16.431 T:5215    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.videomediaset/?mode=canali_live
2021-12-05 23:37:16.442 T:4212    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.videomediaset/?mode=canali_live) failed
```

**Comment by phate89** [comment]
can you tell me the kodi version you are running? it seems an error in bs4 unrelated from the addon
