### ISSUE TITLE
The plugin stopped working with Kodi Nexus

### ISSUE THREAD

**Issue by cinicollerico** [phate89/Mediaset-Play-plugin.video.videomediaset#71]
The plugin stopped working with Kodi Nexus.
Here the log:

```
2023-01-21 15:46:45.604 T:13344   error <general>: CCurlFile::Stat - <http://mirrors.kodi.tv/addons/nexus/plugin.video.eventvods/resources/icon.png> Failed: Timeout was reached(28)
2023-01-21 15:47:23.091 T:15191 warning <general>: CRepository::ParseDirConfiguration: Repository has MD5 hashes enabled - this hash function is broken and will only guard against unintentional data corruption
2023-01-21 15:47:24.263 T:12390    info <general>: Skipped 2 duplicate messages..
2023-01-21 15:47:24.263 T:12390   error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2023-01-21 15:47:24.680 T:15477   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.videomediaset/default.py", line 2, in <module>
                                                       from resources.main import KodiMediaset
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.videomediaset/resources/main.py", line 5, in <module>
                                                       from phate89lib import kodiutils, staticutils  # pylint: disable=import-error
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.phate89/lib/phate89lib/kodiutils.py", line 19, in <module>
                                                       PATH_T = xbmc.translatePath(PATH)
                                                                ^^^^^^^^^^^^^^^^^^
                                                   AttributeError: module 'xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--
```

**Comment by rewe68** [comment]
@phate89 
Will you be able to upgrade the plugin to run on Nexus/Kodi20 soon?

**Comment by yazyazoo** [comment]
https://github.com/CristianSumma/Mediaset-Play-plugin.video.videomediaset

**Comment by phate89** [comment]
I'll soon update the addon thanks to madpilot78, nixxo e cristiansumma that fixed this issue and some more!
